FROM alpine:latest

# install git
RUN apk add --no-cache git

COPY tfsecurity /usr/bin/tfsecurity

## use a non-privileged user
RUN adduser -D tfsecurity
USER tfsecurity

# as we are not specifying an entrypoint, this is the default executed command
# that you could override
CMD [ "tfsecurity", "--help" ]
